[package]
name = "ledgerexport-tax"
version = "0.1.0"
authors = ["Andy Nagels <thereisanewway@gmail.com>"]
edition = "2018"

[dependencies]
docopt = "=1.0.2"
chrono = "0.4"
contracts = "0.3.0"
printpdf = "0.2.8"
